source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'mongoid', '7.0.13'
gem 'rails', '6.1.4'
gem 'puma', '5.0'
gem 'sidekiq', '6.2.1'

gem 'bootsnap', '1.7.5', require: false

group :development do
  # style / security / performance
  gem 'rubocop', '~> 0.82'
  gem 'rubocop-performance', '~> 1.5', require: false
  gem 'rubocop-rails', '~> 2.5', require: false

  gem 'listen', '3.3'
  gem 'spring'
end
